### ISSUE TITLE
Add an SO post watcher

### ISSUE THREAD

**Issue by j-f1** [SOBotics/Redunda#15]
Since several bots need a realtime feed of posts, we could make a websocket that automatically passes the result of calling the API for each post down to the bots.

**Comment by ArtOfCode-** [comment]
https://github.com/SOBotics/apicache

**Comment by j-f1** [comment]
@ArtOfCode- Do you have that hosted somewhere? If not, I could probably figure out hosting.

**Comment by ArtOfCode-** [comment]
@j-f1 temporarily, https://cache.artofcode.co.uk/, moving to https://cache.sobotics.org/ when someone gets time.
