### ISSUE TITLE
Login via redunda.sobotics.org

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#18]
The login does not work correctly via redunda.sobotics.org. The `redirect_uri` needs to be changed

**Comment by ArtOfCode-** [comment]
What does "does not work correctly" mean?

**Comment by NobodyNada** [comment]
@ArtOfCode- It redirects to [redunda.erwaysoftware.com](//redunda.erwaysoftware.com) instead of [redunda.sobotics.org](//redunda.sobotics.org).

**Comment by ArtOfCode-** [comment]
Is that really an issue, given that they both serve precisely the same thing?

**Comment by FelixSFD** [comment]
Yes. Because the cookie is set on redunda.erwaysoftware.com. So you can never be logged in on redunda.sobotics.org

**Comment by Undo1** [comment]
This is pretty hard to fix. You can only have one OAuth domain, so just changing the redirect_uri isn't going to work. We'd need a central place for cookies, and that's not easy.

**Comment by j-f1** [comment]
@Undo1 Why not move to https://redunda.sobotics.org and disable the https://redunda.erwaysoftware.com domain?

**Comment by Undo1** [comment]
@j-f1 We went through this with metasmoke too - conclusion was that I'm *extremely* unlikely to let erwaysoftware.com lapse, since all my email goes through it. We don't have that guarantee with charcoal-se.org or sobotics.org. 

It'd be possible, we just need to decide how much uptime and/or the possibility of dead links matters.

**Comment by FelixSFD** [comment]
redunda.erwaysoftware.com could still be active. But the OAuth domain should be redunda.sobotics.org. So your domain is still the same, but the login only works on .sobotics.org Just like now, but the other way round

**Comment by Undo1** [comment]
Done
