### ISSUE TITLE
Broken layout when there are no active instances

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#38]
<img width="353" alt="bildschirmfoto 2017-03-27 um 19 42 07" src="https://cloud.githubusercontent.com/assets/2721240/24369827/8eb66d7c-1325-11e7-8ab7-3232dffe4f53.png">

On Safari Version 10.1 (12603.1.30.0.34) and Chrome Version 56.0.2924.87 (64-bit)

**Comment by j-f1** [comment]
`!!/blame`
> It’s @j-f1’s fault.

The `<li>` needs the `bot-instance-li` class. I’ll do a refactor to remove the need for that.
