### ISSUE TITLE
Broken layout on instances overview

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#40]
The navigation bar is broken, but only on `/bots/{id}/bot_instances`

![bildschirmfoto 2017-03-29 um 13 16 42](https://cloud.githubusercontent.com/assets/2721240/24452134/0e1884e4-1482-11e7-94ac-70cc69efd211.png)

Still using the same browsers as in #38

**Comment by NobodyNada** [comment]
It's because of a CSS class name conflict.  The class of the instance list is currently `bot-instances`, but it should be called `bot-instances-list`, because the entire body "automatically" has the `bot-instances` class.

I'll try to get around to fixing it today.

**Comment by NobodyNada** [comment]
Fixed by #42
