### ISSUE TITLE
Potential Security Vulnerabilities in Redunda

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Redunda#49]
Received a mail, a couple of days back regarding secy vulnerabilities and seems like 2 dependencies of Redunda are creating a small problem.  The suggested fix is: 

Gemfile.lock update suggested: nokogiri ~> 1.8.1.

Gemfile.lock update suggested: loofah ~> 2.2.1.

**Comment by Fortunate-MAN** [comment]
If there is a possibility of a security vulnerability, wouldn't it be better if you sent an email to the maintainers (Art and Undo?) instead of posting it here? A person could take advantage of the vulnerability (if there is one).

**Comment by Bhargav-Rao** [comment]
Hmm, actually I am not even sure if there's a need of a mail. There's a huge banner, atleast for me, when I visit the repo, telling that there is an issue.

**Comment by Bhargav-Rao** [comment]
@Fortunate-MAN can you look into this issue as well? As this's also related to ruby, I think. 

The issue is still present. There's more secy vulnerabilities in the present mail.

**Comment by Fortunate-MAN** [comment]
@Bhargav-Rao on it.
