### ISSUE TITLE
Add an option to change the username

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Redunda#50]
MS has a route that allows you to change your username without the need to ping someone with database access. The URL is https://metasmoke.erwaysoftware.com/users/username.

Redunda should have such a feature too, if a user wants to change their name.

**Comment by Filnor** [comment]
Or that. Just a way to update it would be nice.

Am Do., 14. Juni 2018 um 17:24 Uhr schrieb Jed Fox <notifications@github.com

**Comment by Undo1** [comment]
It should now trigger an async username update (from SE) on every login. Pretty cheap call, no reason not to send it often.
