### ISSUE TITLE
Error when calling /status.json

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#53]
Calling `/status.json` with a POST request and **a valid key** results in this error:

> Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

Affected line:
https://github.com/SOBotics/Redunda/blob/master/app/controllers/bot_instances_controller.rb#L110

Reproducible with this CURL request:
```
curl -X POST -H 'UserAgent: redunda-lib-java/1.1.0' -d 'key=insert_valid_key_here' -v -i 'https://redunda.sobotics.org/status.json'
```

**Full trace:**

> redis (3.3.5) lib/redis/client.rb:345:in `rescue in establish_connection'
> redis (3.3.5) lib/redis/client.rb:331:in `establish_connection'
> redis (3.3.5) lib/redis/client.rb:101:in `block in connect'
> redis (3.3.5) lib/redis/client.rb:293:in `with_reconnect'
> redis (3.3.5) lib/redis/client.rb:100:in `connect'
> redis (3.3.5) lib/redis/client.rb:364:in `ensure_connected'
> redis (3.3.5) lib/redis/client.rb:221:in `block in process'
> redis (3.3.5) lib/redis/client.rb:306:in `logging'
> redis (3.3.5) lib/redis/client.rb:220:in `process'
> redis (3.3.5) lib/redis/client.rb:120:in `call'
> redis (3.3.5) lib/redis.rb:2130:in `block in publish'
> redis (3.3.5) lib/redis.rb:58:in `block in synchronize'
> /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> redis (3.3.5) lib/redis.rb:58:in `synchronize'
> redis (3.3.5) lib/redis.rb:2129:in `publish'
> actioncable (5.1.6) lib/action_cable/subscription_adapter/redis.rb:22:in `broadcast'
> actioncable (5.1.6) lib/action_cable/subscription_adapter/channel_prefix.rb:6:in `broadcast'
> actioncable (5.1.6) lib/action_cable/server/broadcasting.rb:46:in `block in broadcast'
> activesupport (5.1.6) lib/active_support/notifications.rb:168:in `instrument'
> actioncable (5.1.6) lib/action_cable/server/broadcasting.rb:44:in `broadcast'
> actioncable (5.1.6) lib/action_cable/server/broadcasting.rb:23:in `broadcast'
> app/controllers/bot_instances_controller.rb:110:in `status_ping'
> actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
> actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
> actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
> actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
> activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
> actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
> actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
> actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
> activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
> actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
> actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
> activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
> actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
> actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
> actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
> actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
> actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
> actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
> actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
> actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
> warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
> warden (1.2.7) lib/warden/manager.rb:35:in `catch'
> warden (1.2.7) lib/warden/manager.rb:35:in `call'
> rack (2.0.6) lib/rack/etag.rb:25:in `call'
> rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
> rack (2.0.6) lib/rack/head.rb:12:in `call'
> rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
> rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
> activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
> actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
> railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
> railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
> activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
> activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
> railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
> rack (2.0.6) lib/rack/method_override.rb:22:in `call'
> rack (2.0.6) lib/rack/runtime.rb:22:in `call'
> activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
> actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
> rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
> rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
> railties (5.1.6) lib/rails/engine.rb:522:in `call'
> /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
> /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
> /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
> /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
> /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by ArtOfCode-** [comment]
@Undo1 so apparently Redunda does use Redis...

**Comment by Undo1** [comment]
@FelixSFD Can you give it a try now?

**Comment by FelixSFD** [comment]
Thanks! It works :-)
