### ISSUE TITLE
Unable to create new instances

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Redunda#54]
I was trying to create a new instance of Guttenberg, but when I click on "Save" after filling in the instance name, I get a 

> You are already signed in.

error and the new instance is not created.

**Comment by ArtOfCode-** [comment]
[status-norepro] - I just managed to create an instance called `test`. Got extensions/userscripts that might be interfering?

**Comment by Bhargav-Rao** [comment]
None that I am aware of. Tried without extensions and still the same error. (Chrome on Mac)

**Comment by Undo1** [comment]
Any stacktraces or anything else interesting?

**Comment by Bhargav-Rao** [comment]
Nope, checked the console again. There's no errors.

**Comment by ArtOfCode-** [comment]
Weird. Can you get a screen capture of what happens?

**Comment by Filnor** [comment]
This is happening again now on the new Server. Same repro steps as Bhargav described initially.

**Comment by ArtOfCode-** [comment]
Repro, looking.

**Comment by ArtOfCode-** [comment]
Nginx SSL-forwarding config issue. Should be fixed now.
