### ISSUE TITLE
Error 500 when fetching status

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#62]
Probably related to #53 (even the stacktrace seems to be the same)

When I call `https://redunda.sobotics.org/status.json` with a valid key, the following error occurs:

> Redis::CannotConnectError in BotInstancesController#status_ping
> Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

Sending the version does not affect the result.

**Comment by tripleee** [comment]
I seem to be getting the same in PulseMonitor; is this still the same issue?

https://github.com/Charcoal-SE/PulseMonitor/issues/27

**Comment by ArtOfCode-** [comment]
Should be fixed
